function games() {
  return [
    { name: '10 minutes till dawn', link: 'https://htmlxm.github.io/h7/10-minutes-till-dawn' },
    { name: '11 11', link: 'https://htmlxm.github.io/h2/11-11' },
    { name: '12 minibattles', link: 'https://htmlxm.github.io/h2/12-minibattles' },
    { name: '1v1.xml', link: 'https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/ko1ov/jd83hf02ld65la32mdl4@79c158753f07cf8fae9c1495b040e2a229c7436e/1v1.xml' },
    { name: '2048 multitask', link: 'https://htmlxm.github.io/h7/2048-multitask' },
    { name: '2048', link: 'https://htmlxm.github.io/h/2048' },
    { name: '3d car simulator', link: 'https://htmlxm.github.io/h2/3d-car-simulator' },
    { name: '3d moto simulator 2', link: 'https://htmlxm.github.io/h2/3d-moto-simulator-2' },
    { name: '4th and goal 2022', link: 'https://htmlxm.github.io/h2/4th-and-goal-2022' },
    { name: '4x4 drive offroad', link: 'https://htmlxm.github.io/h7/4x4-drive-offroad' },
    { name: '8 ball pool', link: 'https://htmlxm.github.io/h8/8-ball-pool' },
    { name: 'a dance of fire and ice', link: 'https://htmlxm.github.io/h8/a-dance-of-fire-and-ice' },
    { name: 'a small world cup', link: 'https://htmlxm.github.io/h2/a-small-world-cup' },
    { name: 'adventure drivers', link: 'https://htmlxm.github.io/h7/adventure-drivers' },
    { name: 'age of war', link: 'https://htmlxm.github.io/h8/age-of-war' },
    { name: 'air hockey championship deluxe', link: 'https://htmlxm.github.io/h2/air-hockey-championship-deluxe' },
    { name: 'among us', link: 'https://htmlxm.github.io/h/among-us' },
    { name: 'ape sling', link: 'https://htmlxm.github.io/h2/ape-sling' },
    { name: 'aqua thrills', link: 'https://htmlxm.github.io/h2/aqua-thrills' },
    { name: 'archery world tour', link: 'https://htmlxm.github.io/h/archery-world-tour' },
    { name: 'arithmetica', link: 'https://htmlxm.github.io/h2/arithmetica' },
    { name: 'athletics hero', link: 'https://htmlxm.github.io/h2/athletics-hero' },
    { name: 'awesome tanks 2', link: 'https://htmlxm.github.io/h/awesome-tanks-2' },
    { name: 'awesome tanks', link: 'https://htmlxm.github.io/h/awesome-tanks' },
    { name: 'b cubed', link: 'https://htmlxm.github.io/h/b-cubed' },
    { name: 'basket and ball', link: 'https://htmlxm.github.io/h2/basket-and-ball' },
    { name: 'basket bros', link: 'https://htmlxm.github.io/h7/basket-bros' },
    { name: 'basket champs', link: 'https://htmlxm.github.io/h2/basket-champs' },
    { name: 'basket random', link: 'https://htmlxm.github.io/h8/basket-random' },
    { name: 'basket swooshes', link: 'https://htmlxm.github.io/h2/basket-swooshes' },
    { name: 'basketball legends', link: 'https://htmlxm.github.io/h/basketball-legends' },
    { name: 'basketball line', link: 'https://htmlxm.github.io/h2/basketball-line' },
    { name: 'basketball stars', link: 'https://htmlxm.github.io/h/basketball-stars' },
    { name: 'battle wheels', link: 'https://htmlxm.github.io/h2/battle-wheels' },
    { name: 'bearsus', link: 'https://htmlxm.github.io/h2/bearsus' },
    { name: 'big shot boxing', link: 'https://htmlxm.github.io/h2/big-shot-boxing' },
    { name: 'big tall small', link: 'https://htmlxm.github.io/h8/big-tall-small' },
    { name: 'bike trials offroad 1', link: 'https://htmlxm.github.io/h2/bike-trials-offroad-1' },
    { name: 'bike trials winter 1', link: 'https://htmlxm.github.io/h2/bike-trials-winter-1' },
    { name: 'bike trials winter 2', link: 'https://htmlxm.github.io/h2/bike-trials-winter-2' },
    { name: 'bitlife', link: 'https://htmlxm.github.io/h/bitlife' },
    { name: 'block the pig', link: 'https://htmlxm.github.io/h/block-the-pig' },
    { name: 'blocky cars', link: 'https://htmlxm.github.io/h2/blocky-cars' },
    { name: 'blocky trials', link: 'https://htmlxm.github.io/h2/blocky-trials' },
    { name: 'bloons tower defense 1', link: 'https://htmlxm.github.io/h7/bloons-tower-defense-1' },
    { name: 'bloxorz', link: 'https://htmlxm.github.io/h/bloxorz' },
    { name: 'blumgi ball', link: 'https://htmlxm.github.io/h2/blumgi-ball' },
    { name: 'blumgi castle', link: 'https://htmlxm.github.io/h2/blumgi-castle' },
    { name: 'blumgi rocket', link: 'https://htmlxm.github.io/h2/blumgi-rocket' },
    { name: 'blumgi slime', link: 'https://htmlxm.github.io/h2/blumgi-slime' },
    { name: 'bob the robber 4', link: 'https://htmlxm.github.io/h7/bob-the-robber-4' },
    { name: 'bomb it 7', link: 'https://htmlxm.github.io/h2/bomb-it-7' },
    { name: 'bowling stars', link: 'https://htmlxm.github.io/h2/bowling-stars' },
    { name: 'boxing physics 2', link: 'https://htmlxm.github.io/h2/boxing-physics-2' },
    { name: 'boxing random', link: 'https://htmlxm.github.io/h77/boxing-random' },
    { name: 'brain for monster truck', link: 'https://htmlxm.github.io/h2/brain-for-monster-truck' },
    { name: 'brain test 2 tricky stories', link: 'https://htmlxm.github.io/h2/brain-test-2-tricky-stories' },
    { name: 'brain test 3 tricky quests', link: 'https://htmlxm.github.io/h2/brain-test-3-tricky-quests' },
    { name: 'brain test tricky puzzles', link: 'https://htmlxm.github.io/h2/brain-test-tricky-puzzles' },
    { name: 'breaking the bank', link: 'https://htmlxm.github.io/h7/breaking-the-bank' },
    { name: 'bubble shooter', link: 'https://htmlxm.github.io/h2/bubble-shooter' },
    { name: 'bubble trouble 3', link: 'https://htmlxm.github.io/h2/bubble-trouble-3' },
    { name: 'bubble trouble', link: 'https://htmlxm.github.io/h2/bubble-trouble' },
    { name: 'bullet force', link: 'https://htmlxm.github.io/h7/bullet-force' },
    { name: 'bumper cars soccer', link: 'https://htmlxm.github.io/h2/bumper-cars-soccer' },
    { name: 'bunny hop', link: 'https://htmlxm.github.io/h/bunny-hop' },
    { name: 'burger bounty', link: 'https://htmlxm.github.io/h2/burger-bounty' },
    { name: 'burnin rubber 5 xs', link: 'https://htmlxm.github.io/h2/burnin-rubber-5-xs' },
    { name: 'burnin rubber crash n burn', link: 'https://htmlxm.github.io/h2/burnin-rubber-crash-n-burn' },
    { name: 'burnout drift seaport max', link: 'https://htmlxm.github.io/h2/burnout-drift-seaport-max' },
    { name: 'burrito bison', link: 'https://htmlxm.github.io/h7/burrito-bison' },
    { name: 'candy jump', link: 'https://htmlxm.github.io/h/candy-jump' },
    { name: 'cannon strike', link: 'https://htmlxm.github.io/h2/cannon-strike' },
    { name: 'car climb racing', link: 'https://htmlxm.github.io/h7/car-climb-racing' },
    { name: 'car rush', link: 'https://htmlxm.github.io/h/car-rush' },
    { name: 'cars thief tank edition', link: 'https://htmlxm.github.io/h4/cars-thief-tank-edition' },
    { name: 'cars thief', link: 'https://htmlxm.github.io/h2/cars-thief' },
    { name: 'cat gunner super zombie shoot', link: 'https://htmlxm.github.io/h4/cat-gunner-super-zombie-shoot' },
    { name: 'cat trap', link: 'https://htmlxm.github.io/h8/cat-trap' },
    { name: 'cats', link: 'https://htmlxm.github.io/h4/cats' },
    { name: 'chicken merge', link: 'https://htmlxm.github.io/h4/chicken-merge' },
    { name: 'chrome dino', link: 'https://htmlxm.github.io/h7/chrome-dino' },
    { name: 'city bike stunt 2', link: 'https://htmlxm.github.io/h7/city-bike-stunt-2' },
    { name: 'city car driving stunt master', link: 'https://htmlxm.github.io/h4/city-car-driving-stunt-master' },
    { name: 'city rider', link: 'https://htmlxm.github.io/h4/city-rider' },
    { name: 'cluster rush', link: 'https://htmlxm.github.io/h8/cluster-rush' },
    { name: 'coffee shop', link: 'https://htmlxm.github.io/h/coffee-shop' },
    { name: 'color switch', link: 'https://htmlxm.github.io/h8/color-switch' },
    { name: 'color tunnel 2', link: 'https://htmlxm.github.io/h/color-tunnel-2' },
    { name: 'cookie clicker', link: 'https://htmlxm.github.io/h/cookie-clicker' },
    { name: 'crazy cars', link: 'https://htmlxm.github.io/h4/crazy-cars' },
    { name: 'crazy tunnel 3d', link: 'https://htmlxm.github.io/h4/crazy-tunnel-3d' },
    { name: 'cricket world cup', link: 'https://htmlxm.github.io/h4/cricket-world-cup' },
    { name: 'crossy road', link: 'https://htmlxm.github.io/h/crossy-road' },
    { name: 'cubes king', link: 'https://htmlxm.github.io/h7/cubes-king' },
    { name: 'cubito mayhem', link: 'https://htmlxm.github.io/h7/cubito-mayhem' },
    { name: 'curve ball 3d', link: 'https://htmlxm.github.io/h/curve-ball-3d' },
    { name: 'cyber cars punk racing', link: 'https://htmlxm.github.io/h4/cyber-cars-punk-racing' },
    { name: 'death chase', link: 'https://htmlxm.github.io/h4/death-chase' },
    { name: 'death run 3d', link: 'https://htmlxm.github.io/h7/death-run-3d' },
    { name: 'deepest sword', link: 'https://htmlxm.github.io/h8/deepest-sword' },
    { name: 'deer simulator', link: 'https://htmlxm.github.io/h4/deer-simulator' },
    { name: 'demolition derby crash racing', link: 'https://htmlxm.github.io/h4/demolition-derby-crash-racing' },
    { name: 'detective loupe puzzle', link: 'https://htmlxm.github.io/h4/detective-loupe-puzzle' },
    { name: 'dinosaur game', link: 'https://htmlxm.github.io/h7/dinosaur-game' },
    { name: 'dog simulator 3d', link: 'https://htmlxm.github.io/h4/dog-simulator-3d' },
    { name: 'doge miner', link: 'https://htmlxm.github.io/h7/doge-miner' },
    { name: 'doodle champion island', link: 'https://htmlxm.github.io/h7/doodle-champion-island' },
    { name: 'doodle jump', link: 'https://htmlxm.github.io/h7/doodle-jump' },
    { name: 'draw the hill', link: 'https://htmlxm.github.io/h7/draw-the-hill' },
    { name: 'dreadhead parkour', link: 'https://htmlxm.github.io/h7/dreadhead-parkour' },
    { name: 'drift boss', link: 'https://htmlxm.github.io/h/drift-boss' },
    { name: 'drift hunters', link: 'https://htmlxm.github.io/h/drift-hunters' },
    { name: 'drive mad', link: 'https://htmlxm.github.io/h77/drive-mad' },
    { name: 'drunken duel', link: 'https://htmlxm.github.io/h/drunken-duel' },
    { name: 'duck life 2 world champion', link: 'https://htmlxm.github.io/h/duck-life-2-world-champion' },
    { name: 'duck life 3 evolution', link: 'https://htmlxm.github.io/h/duck-life-3-evolution' },
    { name: 'duck life 4', link: 'https://htmlxm.github.io/h/duck-life-4' },
    { name: 'duck life', link: 'https://htmlxm.github.io/h/duck-life' },
    { name: 'dunkbrush', link: 'https://htmlxm.github.io/h4/dunkbrush' },
    { name: 'dunkers', link: 'https://htmlxm.github.io/h4/dunkers' },
    { name: 'earn to die', link: 'https://htmlxm.github.io/h8/earn-to-die' },
    { name: 'eggy car', link: 'https://htmlxm.github.io/h/eggy-car' },
    { name: 'elastic man', link: 'https://htmlxm.github.io/h7/elastic-man' },
    { name: 'electron dash', link: 'https://htmlxm.github.io/h7/electron-dash' },
    { name: 'eliza mall mania', link: 'https://htmlxm.github.io/h4/eliza-mall-mania' },
    { name: 'energy', link: 'https://htmlxm.github.io/h4/energy' },
    { name: 'escaping the prison', link: 'https://htmlxm.github.io/h7/escaping-the-prison' },
    { name: 'eugenes life', link: 'https://htmlxm.github.io/h4/eugenes-life' },
    { name: 'evo city driving', link: 'https://htmlxm.github.io/h/evo-city-driving' },
    { name: 'extreme car driving simulator', link: 'https://htmlxm.github.io/h7/extreme-car-driving-simulator' },
    { name: 'extreme car parking', link: 'https://htmlxm.github.io/h4/extreme-car-parking' },
    { name: 'factory balls forever', link: 'https://htmlxm.github.io/h/factory-balls-forever' },
    { name: 'fairy dressup', link: 'https://htmlxm.github.io/h4/fairy-dressup' },
    { name: 'fancy pants 2', link: 'https://htmlxm.github.io/h4/fancy-pants-2' },
    { name: 'fancy pants 3', link: 'https://htmlxm.github.io/h4/fancy-pants-3' },
    { name: 'fancy pants', link: 'https://htmlxm.github.io/h4/fancy-pants' },
    { name: 'five nights at freddys 2', link: 'https://htmlxm.github.io/h7/five-nights-at-freddys-2' },
    { name: 'five nights at freddys 3', link: 'https://htmlxm.github.io/h7/five-nights-at-freddys-3' },
    { name: 'five nights at freddys', link: 'https://htmlxm.github.io/h7/five-nights-at-freddys' },
    { name: 'flappy bird origin', link: 'https://htmlxm.github.io/h8/flappy-bird-origin' },
    { name: 'flappy bird', link: 'https://htmlxm.github.io/h2/flappy-bird' },
    { name: 'fleeing the complex', link: 'https://htmlxm.github.io/h7/fleeing-the-complex' },
    { name: 'flying car simulator', link: 'https://htmlxm.github.io/h4/flying-car-simulator' },
    { name: 'foot chinko', link: 'https://htmlxm.github.io/h4/foot-chinko' },
    { name: 'football legends', link: 'https://htmlxm.github.io/h4/football-legends' },
    { name: 'football masters', link: 'https://htmlxm.github.io/h4/football-masters' },
    { name: 'fortz', link: 'https://htmlxm.github.io/h4/fortz' },
    { name: 'free kick shooter', link: 'https://htmlxm.github.io/h4/free-kick-shooter' },
    { name: 'free the key', link: 'https://htmlxm.github.io/h4/free-the-key' },
    { name: 'funny shooter 2', link: 'https://htmlxm.github.io/h4/funny-shooter-2' },
    { name: 'furious racing 3d', link: 'https://htmlxm.github.io/h7/furious-racing-3d' },
    { name: 'g switch 3', link: 'https://htmlxm.github.io/h4/g-switch-3' },
    { name: 'geometry dash', link: 'https://htmlxm.github.io/h8/geometry-dash' },
    { name: 'getaway shootout', link: 'https://htmlxm.github.io/h4/getaway-shootout' },
    { name: 'go kart go ultra', link: 'https://htmlxm.github.io/h4/go-kart-go-ultra' },
    { name: 'gobble', link: 'https://htmlxm.github.io/h4/gobble' },
    { name: 'gold digger frvr', link: 'https://htmlxm.github.io/h4/gold-digger-frvr' },
    { name: 'golf champions', link: 'https://htmlxm.github.io/h4/golf-champions' },
    { name: 'golfinity', link: 'https://htmlxm.github.io/h4/golfinity' },
    { name: 'google feud', link: 'https://htmlxm.github.io/h7/google-feud' },
    { name: 'google snake', link: 'https://htmlxm.github.io/h8/google-snake' },
    { name: 'grand prix hero', link: 'https://htmlxm.github.io/h4/grand-prix-hero' },
    { name: 'gravity soccer', link: 'https://htmlxm.github.io/h4/gravity-soccer' },
    { name: 'grindcraft remastered', link: 'https://htmlxm.github.io/h/grindcraft-remastered' },
    { name: 'grindcraft', link: 'https://htmlxm.github.io/h4/grindcraft' },
    { name: 'gun mayhem 2', link: 'https://htmlxm.github.io/h7/gun-mayhem-2' },
    { name: 'gun mayhem 3', link: 'https://htmlxm.github.io/h7/gun-mayhem-3' },
    { name: 'gun mayhem', link: 'https://htmlxm.github.io/h7/gun-mayhem' },
    { name: 'gunspin', link: 'https://htmlxm.github.io/h/gunspin' },
    { name: 'hammer 2 reloaded', link: 'https://htmlxm.github.io/h4/hammer-2-reloaded' },
    { name: 'happy room', link: 'https://htmlxm.github.io/h7/happy-room' },
    { name: 'head soccer 2023', link: 'https://htmlxm.github.io/h4/head-soccer-2023' },
    { name: 'heads arena soccer all stars', link: 'https://htmlxm.github.io/h4/heads-arena-soccer-all-stars' },
    { name: 'heart star html5', link: 'https://htmlxm.github.io/h4/heart-star-html5' },
    { name: 'hextris', link: 'https://htmlxm.github.io/h7/hextris' },
    { name: 'highway racer 3d', link: 'https://htmlxm.github.io/h5/highway-racer-3d' },
    { name: 'highway rider extreme', link: 'https://htmlxm.github.io/h7/highway-rider-extreme' },
    { name: 'highway traffic', link: 'https://htmlxm.github.io/h7/highway-traffic' },
    { name: 'horse shoeing', link: 'https://htmlxm.github.io/h5/horse-shoeing' },
    { name: 'horse simulator 3d', link: 'https://htmlxm.github.io/h5/horse-simulator-3d' },
    { name: 'house of hazards', link: 'https://htmlxm.github.io/h/house-of-hazards' },
    { name: 'hover racer drive', link: 'https://htmlxm.github.io/h7/hover-racer-drive' },
    { name: 'hover racer', link: 'https://htmlxm.github.io/h/hover-racer' },
    { name: 'icy purple head 3', link: 'https://htmlxm.github.io/h5/icy-purple-head-3' },
    { name: 'idle ants', link: 'https://htmlxm.github.io/h5/idle-ants' },
    { name: 'idle breakout', link: 'https://htmlxm.github.io/h7/idle-breakout' },
    { name: 'idle digging tycoon', link: 'https://htmlxm.github.io/h5/idle-digging-tycoon' },
    { name: 'idle lumber inc', link: 'https://htmlxm.github.io/h5/idle-lumber-inc' },
    { name: 'idle miner', link: 'https://htmlxm.github.io/h5/idle-miner' },
    { name: 'idle mining empire', link: 'https://htmlxm.github.io/h5/idle-mining-empire' },
    { name: 'idle startup tycoon', link: 'https://htmlxm.github.io/h5/idle-startup-tycoon' },
    { name: 'impossible monster truck race', link: 'https://htmlxm.github.io/h5/impossible-monster-truck-race' },
    { name: 'impossible tic tac toe', link: 'https://htmlxm.github.io/h7/impossible-tic-tac-toe' },
    { name: 'infinity loop', link: 'https://htmlxm.github.io/h5/infinity-loop' },
    { name: 'iron snout', link: 'https://htmlxm.github.io/h/iron-snout' },
    { name: 'jelly truck', link: 'https://htmlxm.github.io/h/jelly-truck' },
    { name: 'jet boy', link: 'https://htmlxm.github.io/h/jet-boy' },
    { name: 'jetpack joyride', link: 'https://htmlxm.github.io/h7/jetpack-joyride' },
    { name: 'jollyworld', link: 'https://htmlxm.github.io/h5/jollyworld' },
    { name: 'jumping shell', link: 'https://htmlxm.github.io/h5/jumping-shell' },
    { name: 'kart race 3d', link: 'https://htmlxm.github.io/h7/kart-race-3d' },
    { name: 'kawaii dressup', link: 'https://htmlxm.github.io/h5/kawaii-dressup' },
    { name: 'kix dream soccer', link: 'https://htmlxm.github.io/h5/kix-dream-soccer' },
    { name: 'leader strike', link: 'https://htmlxm.github.io/h7/leader-strike' },
    { name: 'life the game', link: 'https://htmlxm.github.io/h5/life-the-game' },
    { name: 'lemonade stand', link: 'https://htmlxm.github.io/h/lemonade-stand' },
    { name: 'linebacker alley 2', link: 'https://htmlxm.github.io/h5/linebacker-alley-2' },
    { name: 'ludo multiplayer', link: 'https://htmlxm.github.io/h5/ludo-multiplayer' },
    { name: 'mad day', link: 'https://htmlxm.github.io/h2/mad-day' },
    { name: 'mad truck challenge special', link: 'https://htmlxm.github.io/h5/mad-truck-challenge-special' },
    { name: 'madalin stunt cars 2', link: 'https://htmlxm.github.io/h/madalin-stunt-cars-2' },
    { name: 'marble dash', link: 'https://htmlxm.github.io/h5/marble-dash' },
    { name: 'madalin stunt cars 3', link: 'https://htmlxm.github.io/h/madalin-stunt-cars-3' },
    { name: 'masked forces', link: 'https://htmlxm.github.io/h8/masked-forces' },
    { name: 'master chess', link: 'https://htmlxm.github.io/h7/master-chess' },
    { name: 'maze path of light', link: 'https://htmlxm.github.io/h5/maze-path-of-light' },
    { name: 'merge cakes', link: 'https://htmlxm.github.io/h5/merge-cakes' },
    { name: 'maze planet 3d', link: 'https://htmlxm.github.io/h7/maze-planet-3d' },
    { name: 'merge cyber racers', link: 'https://htmlxm.github.io/h5/merge-cyber-racers' },
    { name: 'merge harvest', link: 'https://htmlxm.github.io/h5/merge-harvest' },
    { name: 'minecraft 1.5.2', link: 'https://htmlxm.github.io/h7/minecraft-1.5.2' },
    { name: 'minecraft 1.8.8', link: 'https://htmlxm.github.io/h7/minecraft-1.8.8' },
    { name: 'merge round racers', link: 'https://htmlxm.github.io/h7/merge-round-racers' },
    { name: 'minecraft builder', link: 'https://htmlxm.github.io/h7/minecraft-builder' },
    { name: 'minesweeper', link: 'https://htmlxm.github.io/h7/minesweeper' },
    { name: 'minibattles', link: 'https://htmlxm.github.io/h5/minibattles' },
    { name: 'mob city', link: 'https://htmlxm.github.io/h/mob-city' },
    { name: 'monkey mart', link: 'https://htmlxm.github.io/h8/monkey-mart' },
    { name: 'monster tracks', link: 'https://htmlxm.github.io/h5/monster-tracks' },
    { name: 'monsters wheels special', link: 'https://htmlxm.github.io/h5/monsters-wheels-special' },
    { name: 'mosaic puzzle art', link: 'https://htmlxm.github.io/h5/mosaic-puzzle-art' },
    { name: 'moto maniac 2', link: 'https://htmlxm.github.io/h5/moto-maniac-2' },
    { name: 'moto maniac', link: 'https://htmlxm.github.io/h5/moto-maniac' },
    { name: 'moto road rash 3d', link: 'https://htmlxm.github.io/h7/moto-road-rash-3d' },
    { name: 'moto x3m 2', link: 'https://htmlxm.github.io/h8/moto-x3m-2' },
    { name: 'moto x3m spooky land', link: 'https://htmlxm.github.io/h/moto-x3m-spooky-land' },
    { name: 'moto x3m pool party', link: 'https://htmlxm.github.io/h/moto-x3m-pool-party' },
    { name: 'moto x3m winter', link: 'https://htmlxm.github.io/h/moto-x3m-winter' },
    { name: 'moto x3m', link: 'https://htmlxm.github.io/h8/moto-x3m' },
    { name: 'murder', link: 'https://htmlxm.github.io/h5/murder' },
    { name: 'moto trial racing 2', link: 'https://htmlxm.github.io/h5/moto-trial-racing-2' },
    { name: 'neon war', link: 'https://htmlxm.github.io/h5/neon-war' },
    { name: 'n gon', link: 'https://htmlxm.github.io/h8/n-gon' },
    { name: 'noob drive', link: 'https://htmlxm.github.io/h5/noob-drive' },
    { name: 'onion boy', link: 'https://htmlxm.github.io/h8/onion-boy' },
    { name: 'orbital survival', link: 'https://htmlxm.github.io/h8/orbital-survival' },
    { name: 'offroader v5', link: 'https://htmlxm.github.io/h5/offroader-v5' },
    { name: 'ovo', link: 'https://htmlxm.github.io/h/ovo' },
    { name: 'panda bubble shooter', link: 'https://htmlxm.github.io/h5/panda-bubble-shooter' },
    { name: 'paper fighter 3d', link: 'https://htmlxm.github.io/h9/paper-fighter-3d' },
    { name: 'parking fury 2', link: 'https://htmlxm.github.io/h/parking-fury-2' },
    { name: 'parking fury 3d bounty hunter', link: 'https://htmlxm.github.io/h6/parking-fury-3d-bounty-hunter' },
    { name: 'parking fury 3d night thief', link: 'https://htmlxm.github.io/h6/parking-fury-3d-night-thief' },
    { name: 'penalty kick online', link: 'https://htmlxm.github.io/h/penalty-kick-online' },
    { name: 'penalty shooters 2', link: 'https://htmlxm.github.io/h6/penalty-shooters-2' },
    { name: 'ping pong html5', link: 'https://htmlxm.github.io/h6/ping-pong-html5' },
    { name: 'pixwars 2', link: 'https://htmlxm.github.io/h6/pixwars-2' },
    { name: 'perfect peel', link: 'https://htmlxm.github.io/h6/perfect-peel' },
    { name: 'pixel gun survival', link: 'https://htmlxm.github.io/h9/pixel-gun-survival' },
    { name: 'plactions', link: 'https://htmlxm.github.io/h6/plactions' },
    { name: 'poor bunny', link: 'https://htmlxm.github.io/h6/poor-bunny' },
    { name: 'pop it master', link: 'https://htmlxm.github.io/h6/pop-it-master' },
    { name: 'power badminton', link: 'https://htmlxm.github.io/h6/power-badminton' },
    { name: 'pre civilization bronze age', link: 'https://htmlxm.github.io/h/pre-civilization-bronze-age' },
    { name: 'pool club', link: 'https://htmlxm.github.io/h6/pool-club' },
    { name: 'my pony my little race', link: 'https://htmlxm.github.io/h5/my-pony-my-little-race' },
    { name: 'panda simulator 3d', link: 'https://htmlxm.github.io/h5/panda-simulator-3d' },
    { name: 'precision client', link: 'https://htmlxm.github.io/h9/precision-client' },
    { name: 'paper io 2', link: 'https://htmlxm.github.io/h9/paper-io-2' },
    { name: 'parking fury', link: 'https://htmlxm.github.io/h/parking-fury' },
    { name: 'puppet master', link: 'https://htmlxm.github.io/h6/puppet-master' },
    { name: 'rabbit samurai', link: 'https://htmlxm.github.io/h8/rabbit-samurai' },
    { name: 'raft wars 2', link: 'https://htmlxm.github.io/h6/raft-wars-2' },
    { name: 'raft wars multiplayer', link: 'https://htmlxm.github.io/h6/raft-wars-multiplayer' },
    { name: 'raft wars', link: 'https://htmlxm.github.io/h/raft-wars' },
    { name: 'rally champion', link: 'https://htmlxm.github.io/h6/rally-champion' },
    { name: 'real cars in city', link: 'https://htmlxm.github.io/h6/real-cars-in-city' },
    { name: 'real city driving 2', link: 'https://htmlxm.github.io/h9/real-city-driving-2' },
    { name: 'real simulator monster truck', link: 'https://htmlxm.github.io/h6/real-simulator-monster-truck' },
    { name: 'red ball 4', link: 'https://htmlxm.github.io/h9/red-ball-4' },
    { name: 'recoil', link: 'https://htmlxm.github.io/h6/recoil' },
    { name: 'riddle school', link: 'https://htmlxm.github.io/h9/riddle-school' },
    { name: 'retro bowl', link: 'https://htmlxm.github.io/h/retro-bowl' },
    { name: 'rio rex', link: 'https://htmlxm.github.io/h6/rio-rex' },
    { name: 'parkour block 3d', link: 'https://htmlxm.github.io/h/parkour-block-3d' },
    { name: 'rocket pult', link: 'https://htmlxm.github.io/h9/rocket-pult' },
    { name: 'rocket soccer derby', link: 'https://htmlxm.github.io/h6/rocket-soccer-derby' },
    { name: 'rolling sky', link: 'https://htmlxm.github.io/h6/rolling-sky' },
    { name: 'rolly vortex', link: 'https://htmlxm.github.io/h9/rolly-vortex' },
    { name: 'roly poly monsters', link: 'https://htmlxm.github.io/h6/roly-poly-monsters' },
    { name: 'rooftop snipers 2', link: 'https://htmlxm.github.io/h6/rooftop-snipers-2' },
    { name: 'rooftop snipers', link: 'https://htmlxm.github.io/h/rooftop-snipers' },
    { name: 'rowdy wrestling', link: 'https://htmlxm.github.io/h6/rowdy-wrestling' },
    { name: 'run 3 editor', link: 'https://htmlxm.github.io/h9/run-3-editor' },
    { name: 'running fred', link: 'https://htmlxm.github.io/h6/running-fred' },
    { name: 'rusher crusher', link: 'https://htmlxm.github.io/h6/rusher-crusher' },
    { name: 'sausage flip', link: 'https://htmlxm.github.io/h6/sausage-flip' },
    { name: 'school bus demolition derby', link: 'https://htmlxm.github.io/h6/school-bus-demolition-derby' },
    { name: 'rowdy city wrestling', link: 'https://htmlxm.github.io/h6/rowdy-city-wrestling' },
    { name: 'scrap metal', link: 'https://htmlxm.github.io/h8/scrap-metal' },
    { name: 'shoot stickman', link: 'https://htmlxm.github.io/h9/shoot-stickman' },
    { name: 'short life', link: 'https://htmlxm.github.io/h6/short-life' },
    { name: 'short ride', link: 'https://htmlxm.github.io/h6/short-ride' },
    { name: 'sketchbook 04', link: 'https://htmlxm.github.io/h8/sketchbook-04' },
    { name: 'shortcut race', link: 'https://htmlxm.github.io/h9/shortcut-race' },
    { name: 'skiing fred', link: 'https://htmlxm.github.io/h9/skiing-fred' },
    { name: 'slime road', link: 'https://htmlxm.github.io/h6/slime-road' },
    { name: 'slope 2 multiplayer', link: 'https://htmlxm.github.io/h7/slope-2-multiplayer' },
    { name: 'slope 2', link: 'https://htmlxm.github.io/h6/slope-2' },
    { name: 'slope 3', link: 'https://htmlxm.github.io/h/slope-3' },
    { name: 'slope city', link: 'https://htmlxm.github.io/h7/slope-city' },
    { name: 'slope', link: 'https://htmlxm.github.io/h/slope' },
    { name: 'smash karts', link: 'https://htmlxm.github.io/h/smash-karts' },
    { name: 'soccar', link: 'https://htmlxm.github.io/h6/soccar' },
    { name: 'soccer random', link: 'https://htmlxm.github.io/h8/soccer-random' },
    { name: 'soccer skills champions league', link: 'https://htmlxm.github.io/h6/soccer-skills-champions-league' },
    { name: 'soccer skills euro cup', link: 'https://htmlxm.github.io/h6/soccer-skills-euro-cup' },
    { name: 'solitaire', link: 'https://htmlxm.github.io/h7/solitaire' },
    { name: 'soccer skills world cup', link: 'https://htmlxm.github.io/h6/soccer-skills-world-cup' },
    { name: 'speed boat extreme racing', link: 'https://htmlxm.github.io/h9/speed-boat-extreme-racing' },
    { name: 'squish run', link: 'https://htmlxm.github.io/h6/squish-run' },
    { name: 'sniper gun shooting', link: 'https://htmlxm.github.io/h7/sniper-gun-shooting' },
    { name: 'snow rider 3d', link: 'https://htmlxm.github.io/h8/snow-rider-3d' },
    { name: 'stack ball', link: 'https://htmlxm.github.io/h9/stack-ball' },
    { name: 'stack bump 3d', link: 'https://htmlxm.github.io/h9/stack-bump-3d' },
    { name: 'stacktris', link: 'https://htmlxm.github.io/h6/stacktris' },
    { name: 'stack', link: 'https://htmlxm.github.io/h2/stack' },
    { name: 'stair race 3d', link: 'https://htmlxm.github.io/h6/stair-race-3d' },
    { name: 'stealing the diamond', link: 'https://htmlxm.github.io/h7/stealing-the-diamond' },
    { name: 'stick defenders', link: 'https://htmlxm.github.io/h6/stick-defenders' },
    { name: 'stick fighter', link: 'https://htmlxm.github.io/h6/stick-fighter' },
    { name: 'stick merge', link: 'https://htmlxm.github.io/h3/stick-merge' },
    { name: 'stickman army team battle', link: 'https://htmlxm.github.io/h6/stickman-army-team-battle' },
    { name: 'stickman army the resistance', link: 'https://htmlxm.github.io/h6/stickman-army-the-resistance' },
    { name: 'stickman bike pr', link: 'https://htmlxm.github.io/h6/stickman-bike-pr' },
    { name: 'stickman bike', link: 'https://htmlxm.github.io/h6/stickman-bike' },
    { name: 'stickman boxing ko champion', link: 'https://htmlxm.github.io/h6/stickman-boxing-ko-champion' },
    { name: 'stickman bridge constructor', link: 'https://htmlxm.github.io/h6/stickman-bridge-constructor' },
    { name: 'stickman climb 2', link: 'https://htmlxm.github.io/h6/stickman-climb-2' },
    { name: 'stickman fighter epic battle 2', link: 'https://htmlxm.github.io/h6/stickman-fighter-epic-battle-2' },
    { name: 'stickman fighter mega brawl', link: 'https://htmlxm.github.io/h3/stickman-fighter-mega-brawl' },
    { name: 'stickman golf', link: 'https://htmlxm.github.io/h8/stickman-golf' },
    { name: 'stickman hook', link: 'https://htmlxm.github.io/h/stickman-hook' },
    { name: 'stickman ragdoll crash fun', link: 'https://htmlxm.github.io/h/stickman-ragdoll-crash-fun' },
    { name: 'stickman school run', link: 'https://htmlxm.github.io/h3/stickman-school-run' },
    { name: 'stock car hero', link: 'https://htmlxm.github.io/h3/stock-car-hero' },
    { name: 'street ball jam', link: 'https://htmlxm.github.io/h3/street-ball-jam' },
    { name: 'striker dummies', link: 'https://htmlxm.github.io/h3/striker-dummies' },
    { name: 'stunt car challenge 3', link: 'https://htmlxm.github.io/h3/stunt-car-challenge-3' },
    { name: 'stupid zombies', link: 'https://htmlxm.github.io/h3/stupid-zombies' },
    { name: 'subway runner', link: 'https://htmlxm.github.io/h7/subway-runner' },
    { name: 'subway surfers beijing', link: 'https://htmlxm.github.io/h8/subway-surfers-beijing' },
    { name: 'subway surfers houston', link: 'https://htmlxm.github.io/h8/subway-surfers-houston' },
    { name: 'subway surfers monaco', link: 'https://htmlxm.github.io/h8/subway-surfers-monaco' },
    { name: 'subway surfers newyork', link: 'https://htmlxm.github.io/h8/subway-surfers-newyork' },
    { name: 'subway surfers san francisco', link: 'https://htmlxm.github.io/h8/subway-surfers-san-francisco' },
    { name: 'super bike the champion', link: 'https://htmlxm.github.io/h3/super-bike-the-champion' },
    { name: 'super hexbee merger', link: 'https://htmlxm.github.io/h3/super-hexbee-merger' },
    { name: 'super hot', link: 'https://htmlxm.github.io/h8/super-hot' },
    { name: 'super liquid soccer', link: 'https://htmlxm.github.io/h3/super-liquid-soccer' },
    { name: 'super mario 64', link: 'https://htmlxm.github.io/h9/super-mario-64' },
    { name: 'super mario bros', link: 'https://htmlxm.github.io/h9/super-mario-bros' },
    { name: 'super racing gt drag pro', link: 'https://htmlxm.github.io/h3/super-racing-gt-drag-pro' },
    { name: 'super santa kicker', link: 'https://htmlxm.github.io/h8/super-santa-kicker' },
    { name: 'super star car', link: 'https://htmlxm.github.io/h3/super-star-car' },
    { name: 'super tunnel rush', link: 'https://htmlxm.github.io/h3/super-tunnel-rush' },
    { name: 'superbattle 2', link: 'https://htmlxm.github.io/h3/superbattle-2' },
    { name: 'survivor in rainbow monster', link: 'https://htmlxm.github.io/h3/survivor-in-rainbow-monster' },
    { name: 'superbike hero', link: 'https://htmlxm.github.io/h3/superbike-hero' },
    { name: 'swatforce vs terrorists', link: 'https://htmlxm.github.io/h3/swatforce-vs-terrorists' },
    { name: 'swingo', link: 'https://htmlxm.github.io/h3/swingo' },
    { name: 'tag', link: 'https://htmlxm.github.io/h3/tag' },
    { name: 'tank trouble 2', link: 'https://htmlxm.github.io/h8/tank-trouble-2' },
    { name: 'tanuki sunset', link: 'https://htmlxm.github.io/h8/tanuki-sunset' },
    { name: 'temple of boom', link: 'https://htmlxm.github.io/h3/temple-of-boom' },
    { name: 'temple run 2', link: 'https://htmlxm.github.io/h8/temple-run-2' },
    { name: 'terris', link: 'https://htmlxm.github.io/h9/terris' },
    { name: 'tetris flash', link: 'https://htmlxm.github.io/h7/tetris-flash' },
    { name: 'tennis masters', link: 'https://htmlxm.github.io/h3/tennis-masters' },
    { name: 'the impossible quiz', link: 'https://htmlxm.github.io/h8/the-impossible-quiz' },
    { name: 'the little giant', link: 'https://htmlxm.github.io/h/the-little-giant' },
    { name: 'there is no game', link: 'https://htmlxm.github.io/h/there-is-no-game' },
    { name: 'the spear stickman', link: 'https://htmlxm.github.io/h3/the-spear-stickman' },
    { name: 'three goblets', link: 'https://htmlxm.github.io/h9/three-goblets' },
    { name: 'thumb fighter christmas', link: 'https://htmlxm.github.io/h3/thumb-fighter-christmas' },
    { name: 'thumb fighter', link: 'https://htmlxm.github.io/h3/thumb-fighter' },
    { name: 'tictactoe', link: 'https://htmlxm.github.io/h3/tictactoe' },
    { name: 'tiger simulator 3d', link: 'https://htmlxm.github.io/h3/tiger-simulator-3d' },
    { name: 'tiny fishing', link: 'https://htmlxm.github.io/h/tiny-fishing' },
    { name: 'tinytownracing', link: 'https://htmlxm.github.io/h3/tinytownracing' },
    { name: 'tomb of the mask color', link: 'https://htmlxm.github.io/h8/tomb-of-the-mask-color' },
    { name: 'tomb of the mask', link: 'https://htmlxm.github.io/h8/tomb-of-the-mask' },
    { name: 'toon off', link: 'https://htmlxm.github.io/h3/toon-off' },
    { name: 'top speed 3d', link: 'https://htmlxm.github.io/h3/top-speed-3d' },
    { name: 'top speed racing 3d', link: 'https://htmlxm.github.io/h/top-speed-racing-3d' },
    { name: 'tower of destiny', link: 'https://htmlxm.github.io/h/tower-of-destiny' },
    { name: 'traffic mania', link: 'https://htmlxm.github.io/h3/traffic-mania' },
    { name: 'traffic rider', link: 'https://htmlxm.github.io/h9/traffic-rider' },
    { name: 'tricks', link: 'https://htmlxm.github.io/h3/tricks' },
    { name: 'truck traffic', link: 'https://htmlxm.github.io/h3/truck-traffic' },
    { name: 'tube jumpers', link: 'https://htmlxm.github.io/h3/tube-jumpers' },
    { name: 'tunnel rush', link: 'https://htmlxm.github.io/h/tunnel-rush' },
    { name: 'turbo moto racer', link: 'https://htmlxm.github.io/h9/turbo-moto-racer' },
    { name: 'two ball 3d dark', link: 'https://htmlxm.github.io/h9/two-ball-3d-dark' },
    { name: 'two neon boxes', link: 'https://htmlxm.github.io/h9/two-neon-boxes' },
    { name: 'ultimate car driving', link: 'https://htmlxm.github.io/h9/ultimate-car-driving' },
    { name: 'unicycle hero', link: 'https://htmlxm.github.io/h3/unicycle-hero' },
    { name: 'vex 4', link: 'https://htmlxm.github.io/h9/vex-4' },
    { name: 'vex 6', link: 'https://htmlxm.github.io/h9/vex-6' },
    { name: 'vex 5', link: 'https://htmlxm.github.io/h8/vex-5' },
    { name: 'vex 7', link: 'https://htmlxm.github.io/h9/vex-7' },
    { name: 'volley random', link: 'https://htmlxm.github.io/h9/volley-random' },
    { name: 'volleyball challenge', link: 'https://htmlxm.github.io/h9/volleyball-challenge' },
    { name: 'water color sort', link: 'https://htmlxm.github.io/h3/water-color-sort' },
    { name: 'we become what we behold', link: 'https://htmlxm.github.io/h3/we-become-what-we-behold' },
    { name: 'where is my cat', link: 'https://htmlxm.github.io/h3/where-is-my-cat' },
    { name: 'who is', link: 'https://htmlxm.github.io/h3/who-is' },
    { name: 'wizard mike', link: 'https://htmlxm.github.io/h3/wizard-mike' },
    { name: 'wood blocks 3d', link: 'https://htmlxm.github.io/h3/wood-blocks-3d' },
    { name: 'word city crossed', link: 'https://htmlxm.github.io/h3/word-city-crossed' },
    { name: 'word city uncrossed', link: 'https://htmlxm.github.io/h3/word-city-uncrossed' },
    { name: 'wordle unlimited', link: 'https://htmlxm.github.io/h9/wordle-unlimited' },
    { name: 'words search classic edition', link: 'https://htmlxm.github.io/h3/words-search-classic-edition' },
    { name: 'worlds hardest game 2', link: 'https://htmlxm.github.io/h/worlds-hardest-game-2' },
    { name: 'worlds hardest game 3', link: 'https://htmlxm.github.io/h/worlds-hardest-game-3' },
    { name: 'wrassling', link: 'https://htmlxm.github.io/h3/wrassling' },
    { name: 'zombie derby pixel survival', link: 'https://htmlxm.github.io/h3/zombie-derby-pixel-survival' },
    { name: 'sis.xml', link: 'https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://26515722-282596139816136697.preview.editmysite.com/uploads/b/7547235-562404422326578714/files/sis.xml' },
    { name: 'snowball.xml', link: 'https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/gertdoro/SQLite4Unity3d@8516fc0bd1d2be662ca484f5dc506268b24763ef/Example/Assets/snowball.xml' },
    { name: 'ts3.xml', link: 'https://google-opensocial.googleusercontent.com/gadgets/ifr?url=https://cdn.jsdelivr.net/gh/sk1bx/version@0d8fb9c7430567ed0900902593eee6ba2ba8d297/ts3.xml' },
    { name: '18 wheeler cargo simulator', link: 'https://topvz.github.io/g72/18-wheeler-cargo-simulator' },
    { name: '1v1 lol offline', link: 'https://topvz.github.io/g77/1v1-lol-offline' },
    { name: '2 minute football', link: 'https://topvz.github.io/g17/2-minute-football' },
    { name: '3d monster truck skyroads', link: 'https://topvz.github.io/g26/3d-monster-truck-skyroads' },
    { name: 'archer master 3d castle defense', link: 'https://topvz.github.io/g26/archer-master-3d-castle-defense' },
    { name: 'avalanche', link: 'https://topvz.github.io/g17/avalanche' },
    { name: 'bacon may die', link: 'https://topvz.github.io/g26/bacon-may-die' },
    { name: 'basketball frvr', link: 'https://topvz.github.io/g26/basketball-frvr' },
    { name: 'battle golf', link: 'https://topvz.github.io/g17/battle-golf' },
    { name: 'blobby clicker', link: 'https://topvz.github.io/g72/blobby-clicker' },
    { name: 'blumgi dragon', link: 'https://topvz.github.io/g17/blumgi-dragon' },
    { name: 'bouncy basketball', link: 'https://topvz.github.io/g26/bouncy-basketball' },
    { name: 'boxrob 2', link: 'https://topvz.github.io/g26/boxrob-2' },
    { name: 'boxrob 3', link: 'https://topvz.github.io/g26/boxrob-3' },
    { name: 'boxrob', link: 'https://topvz.github.io/g26/boxrob' },
    { name: 'bubbles cool', link: 'https://topvz.github.io/g17/bubbles-cool' },
    { name: 'burnout extreme drift 2', link: 'https://topvz.github.io/g26/burnout-extreme-drift-2' },
    { name: 'car drift racers 2', link: 'https://topvz.github.io/g72/car-drift-racers-2' },
    { name: 'car eats car winter adventure', link: 'https://topvz.github.io/g17/car-eats-car-winter-adventure' },
    { name: 'car simulator arena', link: 'https://topvz.github.io/g72/car-simulator-arena' },
    { name: 'catpad', link: 'https://topvz.github.io/g17/catpad' },
    { name: 'colorup', link: 'https://topvz.github.io/g72/colorup' },
    { name: 'cow bay', link: 'https://topvz.github.io/g72/cow-bay' },
    { name: 'cozy room design', link: 'https://topvz.github.io/g72/cozy-room-design' },
    { name: 'craftomation 1', link: 'https://topvz.github.io/g72/craftomation-1' },
    { name: 'dark runner', link: 'https://topvz.github.io/g17/dark-runner' },
    { name: 'descent', link: 'https://topvz.github.io/g17/descent' },
    { name: 'detective dan', link: 'https://topvz.github.io/g72/detective-dan' },
    { name: 'dino bros', link: 'https://topvz.github.io/g72/dino-bros' },
    { name: 'double panda', link: 'https://topvz.github.io/g26/double-panda' },
    { name: 'dragon simulator 3d', link: 'https://topvz.github.io/g26/dragon-simulator-3d' },
    { name: 'dubai police parking 2', link: 'https://topvz.github.io/g72/dubai-police-parking-2' },
    { name: 'dunk perfect', link: 'https://topvz.github.io/g17/dunk-perfect' },
    { name: 'duo survival 2', link: 'https://topvz.github.io/g72/duo-survival-2' },
    { name: 'duo survival 3', link: 'https://topvz.github.io/g26/duo-survival-3' },
    { name: 'duo survival', link: 'https://topvz.github.io/g72/duo-survival' },
    { name: 'duo vikings 2', link: 'https://topvz.github.io/g72/duo-vikings-2' },
    { name: 'duo vikings 3', link: 'https://topvz.github.io/g72/duo-vikings-3' },
    { name: 'duo vikings', link: 'https://topvz.github.io/g72/duo-vikings' },
    { name: 'element blocks', link: 'https://topvz.github.io/g72/element-blocks' },
    { name: 'extreme off road cars 3 cargo', link: 'https://topvz.github.io/g72/extreme-off-road-cars-3-cargo' },
    { name: 'extreme off road cars', link: 'https://topvz.github.io/g72/extreme-off-road-cars' },
    { name: 'fireboy and watergirl 1 forest temple', link: 'https://topvz.github.io/g26/fireboy-and-watergirl-1-forest-temple' },
    { name: 'fireboy and watergirl 2 light temple', link: 'https://topvz.github.io/g26/fireboy-and-watergirl-2-light-temple' },
    { name: 'fireboy and watergirl 4 crystal temple', link: 'https://topvz.github.io/g26/fireboy-and-watergirl-4-crystal-temple' },
    { name: 'fireboy and watergirl 5 elements', link: 'https://topvz.github.io/g26/fireboy-and-watergirl-5-elements' },
    { name: 'fireboy watergirl 3 ice temple', link: 'https://topvz.github.io/g26/fireboy-watergirl-3-ice-temple' },
    { name: 'fireboy watergirl 6 fairy tales', link: 'https://topvz.github.io/g26/fireboy-watergirl-6-fairy-tales' },
    { name: 'flip bros', link: 'https://topvz.github.io/g17/flip-bros' },
    { name: 'flip runner', link: 'https://topvz.github.io/g26/flip-runner' },
    { name: 'fnf b sides', link: 'https://topvz.github.io/fnf3/fnf-b-sides' },
    { name: 'fnf hatsune miku', link: 'https://topvz.github.io/fnf3/fnf-hatsune-miku' },
    { name: 'fnf shaggy matt', link: 'https://topvz.github.io/fnf3/fnf-shaggy-matt' },
    { name: 'fnf week 7', link: 'https://topvz.github.io/fnf3/fnf-week-7' },
    { name: 'fnf xe', link: 'https://topvz.github.io/fnf3/fnf-xe' },
    { name: 'football blitz', link: 'https://topvz.github.io/g17/football-blitz' },
    { name: 'fortride open world', link: 'https://topvz.github.io/g72/fortride-open-world' },
    { name: 'four in a row', link: 'https://topvz.github.io/g17/four-in-a-row' },
    { name: 'fox simulator 3d', link: 'https://topvz.github.io/g26/fox-simulator-3d' },
    { name: 'fury wars', link: 'https://topvz.github.io/g17/fury-wars' },
    { name: 'g switch 4', link: 'https://topvz.github.io/g17/g-switch-4' },
    { name: 'hide and smash', link: 'https://topvz.github.io/g17/hide-and-smash' },
    { name: 'highway bike simulator', link: 'https://topvz.github.io/g72/highway-bike-simulator' },
    { name: 'hills of steel', link: 'https://topvz.github.io/g17/hills-of-steel' },
    { name: 'hypersnake', link: 'https://topvz.github.io/g17/hypersnake' },
    { name: 'idle zoo safari rescue', link: 'https://topvz.github.io/g72/idle-zoo-safari-rescue' },
    { name: 'izowave build and defend', link: 'https://topvz.github.io/g72/izowave-build-and-defend' },
    { name: 'james gun', link: 'https://topvz.github.io/g17/james-gun' },
    { name: 'just park it 11', link: 'https://topvz.github.io/g72/just-park-it-11' },
    { name: 'just park it 12', link: 'https://topvz.github.io/g26/just-park-it-12' },
    { name: 'kart wars', link: 'https://topvz.github.io/g17/kart-wars' },
    { name: 'lands of blight', link: 'https://topvz.github.io/g26/lands-of-blight' },
    { name: 'level devil', link: 'https://topvz.github.io/g17/level-devil' },
    { name: 'little master cricket', link: 'https://topvz.github.io/g17/little-master-cricket' },
    { name: 'lurkers io', link: 'https://topvz.github.io/g72/lurkers-io' },
    { name: 'make it meme', link: 'https://topvz.github.io/g17/make-it-meme' },
    { name: 'merge party', link: 'https://topvz.github.io/g72/merge-party' },
    { name: 'misland', link: 'https://topvz.github.io/g17/misland' },
    { name: 'monster truck racing arena', link: 'https://topvz.github.io/g26/monster-truck-racing-arena' },
    { name: 'moto space racing 2 player', link: 'https://topvz.github.io/g26/moto-space-racing-2-player' },
    { name: 'moving truck bounty', link: 'https://topvz.github.io/g26/moving-truck-bounty' },
    { name: 'mystical birdlink', link: 'https://topvz.github.io/g17/mystical-birdlink' },
    { name: 'narrow one', link: 'https://topvz.github.io/g17/narrow-one' },
    { name: 'noob hook', link: 'https://topvz.github.io/g17/noob-hook' },
    { name: 'odd bot out', link: 'https://topvz.github.io/g17/odd-bot-out' },
    { name: 'off road rain cargo simulator', link: 'https://topvz.github.io/g72/off-road-rain-cargo-simulator' },
    { name: 'orange', link: 'https://topvz.github.io/g72/orange' },
    { name: 'pack a bag', link: 'https://topvz.github.io/g72/pack-a-bag' },
    { name: 'paper minecraft', link: 'https://topvz.github.io/g77/paper-minecraft' },
    { name: 'parking fury 3d beach city', link: 'https://topvz.github.io/g72/parking-fury-3d-beach-city' },
    { name: 'parking fury 3d', link: 'https://topvz.github.io/g72/parking-fury-3d' },
    { name: 'parkmania', link: 'https://topvz.github.io/g17/parkmania' },
    { name: 'parkour race', link: 'https://topvz.github.io/g72/parkour-race' },
    { name: 'partytoons', link: 'https://topvz.github.io/g17/partytoons' },
    { name: 'peppa pig basketball', link: 'https://topvz.github.io/g72/peppa-pig-basketball' },
    { name: 'perfect dunk', link: 'https://topvz.github.io/g26/perfect-dunk' },
    { name: 'rainbow obby', link: 'https://topvz.github.io/g17/rainbow-obby' },
    { name: 'retro highway', link: 'https://topvz.github.io/g17/retro-highway' },
    { name: 'rugby rush', link: 'https://topvz.github.io/g17/rugby-rush' },
    { name: 'runman race around the world', link: 'https://topvz.github.io/g72/runman-race-around-the-world' },
    { name: 'scrap divers', link: 'https://topvz.github.io/g72/scrap-divers' },
    { name: 'shady bears', link: 'https://topvz.github.io/g17/shady-bears' },
    { name: 'shape fold animals', link: 'https://topvz.github.io/g26/shape-fold-animals' },
    { name: 'shape fold html5', link: 'https://topvz.github.io/g26/shape-fold-html5' },
    { name: 'shape fold nature', link: 'https://topvz.github.io/g26/shape-fold-nature' },
    { name: 'sharkio', link: 'https://topvz.github.io/g17/sharkio' },
    { name: 'shootz', link: 'https://topvz.github.io/g17/shootz' },
    { name: 'skibidi shooter', link: 'https://topvz.github.io/g17/skibidi-shooter' },
    { name: 'slalom hero', link: 'https://topvz.github.io/g17/slalom-hero' },
    { name: 'slime laboratory', link: 'https://topvz.github.io/g17/slime-laboratory' },
    { name: 'sling drift', link: 'https://topvz.github.io/g26/sling-drift' },
    { name: 'slope tunnel', link: 'https://topvz.github.io/g6/slope-tunnel' },
    { name: 'slopey', link: 'https://topvz.github.io/g17/slopey' },
    { name: 'slot car racing', link: 'https://topvz.github.io/g26/slot-car-racing' },
    { name: 'snail bob 6', link: 'https://topvz.github.io/g72/snail-bob-6' },
    { name: 'snake is mlg edition', link: 'https://topvz.github.io/g17/snake-is-mlg-edition' },
    { name: 'stickman crazy box', link: 'https://topvz.github.io/g17/stickman-crazy-box' },
    { name: 'stickman fight ragdoll', link: 'https://topvz.github.io/g26/stickman-fight-ragdoll' },
    { name: 'super mx the champion', link: 'https://topvz.github.io/g26/super-mx-the-champion' },
    { name: 'superbrawl', link: 'https://topvz.github.io/g17/superbrawl' },
    { name: 'supernova', link: 'https://topvz.github.io/g17/supernova' },
    { name: 'tag 2', link: 'https://topvz.github.io/g17/tag-2' },
    { name: 'tetra blocks', link: 'https://topvz.github.io/g17/tetra-blocks' },
    { name: 'tetris 99', link: 'https://topvz.github.io/g72/tetris-99' },
    { name: 'tetris', link: 'https://topvz.github.io/g77/tetris' },
    { name: 'throw it higher', link: 'https://topvz.github.io/g17/throw-it-higher' },
    { name: 'touchdowners', link: 'https://topvz.github.io/g17/touchdowners' },
    { name: 'traffic escape', link: 'https://topvz.github.io/g17/traffic-escape' },
    { name: 'traffic rush', link: 'https://topvz.github.io/g17/traffic-rush' },
    { name: 'truck loader 2', link: 'https://topvz.github.io/g26/truck-loader-2' },
    { name: 'truck loader 3', link: 'https://topvz.github.io/g26/truck-loader-3' },
    { name: 'truck loader 4', link: 'https://topvz.github.io/g26/truck-loader-4' },
    { name: 'truck loader 5', link: 'https://topvz.github.io/g26/truck-loader-5' },
    { name: 'truck loader', link: 'https://topvz.github.io/g26/truck-loader' },
    { name: 'two button bounce', link: 'https://topvz.github.io/g17/two-button-bounce' },
    { name: 'vectaria io', link: 'https://topvz.github.io/g17/vectaria-io' },
    { name: 'village craft', link: 'https://topvz.github.io/g17/village-craft' },
    { name: 'war of caribbean pirates', link: 'https://topvz.github.io/g26/war-of-caribbean-pirates' },
    { name: 'yohoho io', link: 'https://topvz.github.io/g17/yohoho-io' },
    { name: 'zeepkist crash 2d', link: 'https://topvz.github.io/g17/zeepkist-crash-2d' },
    { name: 'zombie siege outbreak', link: 'https://topvz.github.io/g26/zombie-siege-outbreak' },
    { name: 'zombotag', link: 'https://topvz.github.io/g26/zombotag' },
    { name: 'zoom be 2', link: 'https://topvz.github.io/g26/zoom-be-2' },
    { name: 'zoom be 3', link: 'https://topvz.github.io/g26/zoom-be-3' },
    { name: 'zoom be', link: 'https://topvz.github.io/g72/zoom-be' },
    ];
}
function performSearch() {
    var searchQuery = document.getElementById('search').value.toLowerCase();
    var fileLinks = games();
    var searchResultsDiv = document.getElementById('searchResults');
    searchResultsDiv.innerHTML = ""; 

    for (var i = 0; i < fileLinks.length; i++) {
        var fileName = fileLinks[i].name.toLowerCase();

        if (fileName.includes(searchQuery)) {
          var resultItem = document.createElement('a');
          resultItem.textContent = fileLinks[i].name;
          resultItem.href = fileLinks[i].link;
          searchResultsDiv.appendChild(resultItem);
        }
    }
}
function openq() {
  document.getElementById("Quickaccess").style.width = "250px";
}
function closeq() {
  document.getElementById("Quickaccess").style.width = "0";
}
var currentPage = window.location.pathname;
var visitedPages = JSON.parse(localStorage.getItem('visitedPages')) || [];
var pageIndex = visitedPages.indexOf(currentPage);
if (pageIndex !== -1) {
  visitedPages.splice(pageIndex, 1);
}
visitedPages.unshift(currentPage);
localStorage.setItem('visitedPages', JSON.stringify(visitedPages));



function gra(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'none';
  darkb.style.display = 'block';
  lightb.style.display = 'none';
  bodyElement.classList = [];
  bodyElement.classList.add("gra");
  window.sessionStorage.background = "gra";
}
function dark(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'none';
  darkb.style.display = 'none';
  lightb.style.display = 'block';
  bodyElement.classList = [];
  bodyElement.classList.add("dark");
  window.sessionStorage.background = "dark";
}
function light(){
  var bodyElement = document.body;
  var grab = document.getElementById('gra');
  var darkb = document.getElementById('dark');
  var lightb = document.getElementById('light');
  grab.style.display = 'block';
  darkb.style.display = 'none';
  lightb.style.display = 'none';
  bodyElement.classList = [];
  bodyElement.classList.add("light");
  window.sessionStorage.background = "light";
}
if (window.sessionStorage.background == "gra"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("gra");
}else if (window.sessionStorage.background == "light"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("light");
}else if (window.sessionStorage.background == "dark"){
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  var bodyElement = document.body;
  bodyElement.classList = [];
  bodyElement.classList.add("dark");
}else{
  var bodyElement = document.body;
  var fullPath = window.location.pathname;
  var fileName = fullPath.split('/').pop();
  bodyElement.classList.add("gra");
  window.sessionStorage.background = "gra";
}
